addons:
  apt:
    packages:
      - xvfb
language: node_js
node_js:
  - 0.12
  - 4
  - 5

before_install:
  - npm install npm@latest -g
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
